// ============================================
// THE UNDERGROWTH — Entity Definitions
// All enemies and items in the game
// ============================================

import { EnemyDef, ItemDef } from './types';

// ---- ITEMS ----
export const ITEMS: ItemDef[] = [
  // --- Consumables ---
  {
    id: 'health_moss',
    name: 'Healing Moss',
    icon: '🌿',
    description: 'A clump of bioluminescent moss that mends wounds.',
    type: 'consumable',
    healAmount: 15,
    rarity: 'common',
    floorMin: 1,
  },
  {
    id: 'glowcap_elixir',
    name: 'Glowcap Elixir',
    icon: '🧪',
    description: 'A potent fungal brew that restores vitality.',
    type: 'consumable',
    healAmount: 40,
    rarity: 'uncommon',
    floorMin: 3,
  },
  {
    id: 'spore_bomb',
    name: 'Spore Bomb',
    icon: '💥',
    description: 'Explodes in a cloud of toxic spores, damaging nearby enemies.',
    type: 'scroll',
    scrollEffect: 'fireball',
    rarity: 'uncommon',
    floorMin: 2,
  },
  {
    id: 'luminous_draught',
    name: 'Luminous Draught',
    icon: '✨',
    description: 'Reveals the entire floor map.',
    type: 'scroll',
    scrollEffect: 'reveal_map',
    rarity: 'rare',
    floorMin: 3,
  },
  {
    id: 'mycelium_wrap',
    name: 'Mycelium Wrap',
    icon: '🩹',
    description: 'Living bandage that heals over time.',
    type: 'consumable',
    statusEffect: { type: 'regen', turnsLeft: 10, value: 3 },
    rarity: 'uncommon',
    floorMin: 2,
  },
  {
    id: 'cave_lichen',
    name: 'Strength Lichen',
    icon: '💪',
    description: 'Temporarily boosts attack power.',
    type: 'consumable',
    statusEffect: { type: 'strength', turnsLeft: 15, value: 4 },
    rarity: 'uncommon',
    floorMin: 3,
  },
  {
    id: 'blink_spore',
    name: 'Blink Spore',
    icon: '🌀',
    description: 'Teleports you to a random safe location.',
    type: 'scroll',
    scrollEffect: 'teleport',
    rarity: 'rare',
    floorMin: 2,
  },
  {
    id: 'frost_truffle',
    name: 'Frost Truffle',
    icon: '❄️',
    description: 'Freezes all enemies on the floor for a few turns.',
    type: 'scroll',
    scrollEffect: 'freeze_all',
    rarity: 'rare',
    floorMin: 5,
  },
  {
    id: 'mega_elixir',
    name: 'Primordial Nectar',
    icon: '💎',
    description: 'Fully restores health and grants a shield.',
    type: 'consumable',
    healAmount: 999,
    statusEffect: { type: 'shield', turnsLeft: 10, value: 5 },
    rarity: 'legendary',
    floorMin: 8,
  },

  // --- Weapons ---
  {
    id: 'stone_knife',
    name: 'Stone Knife',
    icon: '🔪',
    description: 'A crude blade chipped from cave rock.',
    type: 'equipment',
    equipSlot: 'weapon',
    atkBonus: 2,
    rarity: 'common',
    floorMin: 1,
  },
  {
    id: 'bone_club',
    name: 'Bone Club',
    icon: '🦴',
    description: 'A heavy femur from some unfortunate beast.',
    type: 'equipment',
    equipSlot: 'weapon',
    atkBonus: 3,
    rarity: 'common',
    floorMin: 1,
  },
  {
    id: 'fungal_blade',
    name: 'Fungal Blade',
    icon: '⚔️',
    description: 'A sword grown from hardened mycelium. Razor-sharp.',
    type: 'equipment',
    equipSlot: 'weapon',
    atkBonus: 5,
    rarity: 'uncommon',
    floorMin: 3,
  },
  {
    id: 'crystal_axe',
    name: 'Crystal Axe',
    icon: '🪓',
    description: 'An axe head of pure cave crystal, glowing faintly.',
    type: 'equipment',
    equipSlot: 'weapon',
    atkBonus: 8,
    rarity: 'rare',
    floorMin: 5,
  },
  {
    id: 'abyssal_fang',
    name: 'Abyssal Fang',
    icon: '🗡️',
    description: 'A tooth from something that should not exist. Hums with power.',
    type: 'equipment',
    equipSlot: 'weapon',
    atkBonus: 13,
    rarity: 'legendary',
    floorMin: 8,
  },

  // --- Armor ---
  {
    id: 'bark_vest',
    name: 'Bark Vest',
    icon: '🪵',
    description: 'Woven bark strips offer basic protection.',
    type: 'equipment',
    equipSlot: 'armor',
    defBonus: 2,
    rarity: 'common',
    floorMin: 1,
  },
  {
    id: 'chitin_mail',
    name: 'Chitin Mail',
    icon: '🛡️',
    description: 'Armor plates harvested from giant cave beetles.',
    type: 'equipment',
    equipSlot: 'armor',
    defBonus: 4,
    rarity: 'uncommon',
    floorMin: 3,
  },
  {
    id: 'mycelium_plate',
    name: 'Mycelium Plate',
    icon: '🧥',
    description: 'Dense fungal armor that regenerates over time.',
    type: 'equipment',
    equipSlot: 'armor',
    defBonus: 7,
    hpBonus: 10,
    rarity: 'rare',
    floorMin: 5,
  },
  {
    id: 'abyssal_carapace',
    name: 'Abyssal Carapace',
    icon: '🦠',
    description: 'Armor of living darkness. It watches back.',
    type: 'equipment',
    equipSlot: 'armor',
    defBonus: 12,
    hpBonus: 25,
    rarity: 'legendary',
    floorMin: 8,
  },

  // --- Accessories ---
  {
    id: 'glowstone_ring',
    name: 'Glowstone Ring',
    icon: '💍',
    description: 'Extends your field of vision slightly.',
    type: 'equipment',
    equipSlot: 'accessory',
    hpBonus: 5,
    rarity: 'common',
    floorMin: 2,
  },
  {
    id: 'spore_amulet',
    name: 'Spore Amulet',
    icon: '📿',
    description: 'A pendant that pulses with fungal energy. Boosts all stats.',
    type: 'equipment',
    equipSlot: 'accessory',
    atkBonus: 2,
    defBonus: 2,
    hpBonus: 10,
    rarity: 'rare',
    floorMin: 5,
  },
  {
    id: 'heart_of_undergrowth',
    name: 'Heart of the Undergrowth',
    icon: '💠',
    description: 'The living core of the mycelium network. Immense power.',
    type: 'equipment',
    equipSlot: 'accessory',
    atkBonus: 5,
    defBonus: 5,
    hpBonus: 30,
    rarity: 'legendary',
    floorMin: 9,
  },

  // --- Keys ---
  {
    id: 'cave_key',
    name: 'Cave Key',
    icon: '🗝️',
    description: 'A rusty key. Opens locked chests.',
    type: 'key',
    rarity: 'common',
    floorMin: 1,
  },
];

export function getItemDef(id: string): ItemDef | undefined {
  return ITEMS.find(i => i.id === id);
}

// ---- ENEMIES ----
export const ENEMIES: EnemyDef[] = [
  // --- Floor 1-3: Cave Critters ---
  {
    id: 'cave_rat',
    name: 'Cave Rat',
    icon: '🐀',
    description: 'A scrawny rodent with glowing eyes.',
    baseHp: 8,
    baseAtk: 2,
    baseDef: 0,
    xpReward: 5,
    speed: 1,
    behavior: 'wander',
    drops: [{ itemId: 'health_moss', chance: 0.3 }],
    floorMin: 1,
    floorMax: 4,
  },
  {
    id: 'glow_beetle',
    name: 'Glow Beetle',
    icon: '🪲',
    description: 'A luminescent beetle with sharp mandibles.',
    baseHp: 12,
    baseAtk: 3,
    baseDef: 1,
    xpReward: 8,
    speed: 1,
    behavior: 'chase',
    drops: [{ itemId: 'health_moss', chance: 0.2 }],
    floorMin: 1,
    floorMax: 5,
  },
  {
    id: 'spore_bat',
    name: 'Spore Bat',
    icon: '🦇',
    description: 'Erratic flight makes it hard to hit.',
    baseHp: 6,
    baseAtk: 4,
    baseDef: 0,
    xpReward: 7,
    speed: 1,
    behavior: 'wander',
    drops: [],
    floorMin: 1,
    floorMax: 5,
  },

  // --- Floor 2-5: Fungal Creatures ---
  {
    id: 'mushroom_walker',
    name: 'Mushroom Walker',
    icon: '🍄',
    description: 'An ambulatory fungus that shambles toward you.',
    baseHp: 20,
    baseAtk: 4,
    baseDef: 2,
    xpReward: 12,
    speed: 1,
    behavior: 'chase',
    drops: [{ itemId: 'health_moss', chance: 0.4 }, { itemId: 'cave_key', chance: 0.1 }],
    floorMin: 2,
    floorMax: 6,
  },
  {
    id: 'acid_slug',
    name: 'Acid Slug',
    icon: '🐛',
    description: 'Leaves a corrosive trail. Slow but deadly.',
    baseHp: 25,
    baseAtk: 6,
    baseDef: 1,
    xpReward: 15,
    speed: 2, // moves every other turn
    behavior: 'chase',
    drops: [{ itemId: 'spore_bomb', chance: 0.15 }],
    floorMin: 2,
    floorMax: 7,
  },
  {
    id: 'cave_spider',
    name: 'Cave Spider',
    icon: '🕷️',
    description: 'Waits in ambush, then strikes with venomous fangs.',
    baseHp: 14,
    baseAtk: 5,
    baseDef: 1,
    xpReward: 12,
    speed: 1,
    behavior: 'ambush',
    drops: [{ itemId: 'mycelium_wrap', chance: 0.15 }],
    floorMin: 2,
    floorMax: 6,
  },

  // --- Floor 4-7: Deep Dwellers ---
  {
    id: 'crystal_golem',
    name: 'Crystal Golem',
    icon: '🪨',
    description: 'Animated cave crystals. Extremely tough.',
    baseHp: 40,
    baseAtk: 7,
    baseDef: 5,
    xpReward: 25,
    speed: 2,
    behavior: 'patrol',
    drops: [{ itemId: 'crystal_axe', chance: 0.08 }],
    floorMin: 4,
    floorMax: 8,
  },
  {
    id: 'phantom_spore',
    name: 'Phantom Spore',
    icon: '👻',
    description: 'A ghostly mass of spores. Partially intangible.',
    baseHp: 18,
    baseAtk: 8,
    baseDef: 0,
    xpReward: 20,
    speed: 1,
    behavior: 'chase',
    drops: [{ itemId: 'blink_spore', chance: 0.2 }],
    floorMin: 4,
    floorMax: 9,
  },
  {
    id: 'fungal_horror',
    name: 'Fungal Horror',
    icon: '🦑',
    description: 'A writhing mass of tentacles and mycelium.',
    baseHp: 35,
    baseAtk: 9,
    baseDef: 3,
    xpReward: 30,
    speed: 1,
    behavior: 'chase',
    abilities: [{ name: 'Toxic Cloud', type: 'aoe', value: 4, cooldown: 4, range: 2 }],
    drops: [{ itemId: 'cave_lichen', chance: 0.25 }],
    floorMin: 5,
    floorMax: 10,
  },

  // --- Floor 7-10: Abyssal Terrors ---
  {
    id: 'deep_crawler',
    name: 'Deep Crawler',
    icon: '🦂',
    description: 'An enormous centipede-like creature from the deepest caves.',
    baseHp: 50,
    baseAtk: 12,
    baseDef: 5,
    xpReward: 40,
    speed: 1,
    behavior: 'chase',
    drops: [{ itemId: 'glowcap_elixir', chance: 0.3 }],
    floorMin: 7,
    floorMax: 12,
  },
  {
    id: 'shadow_stalker',
    name: 'Shadow Stalker',
    icon: '🌑',
    description: 'You only see it when it attacks. By then it may be too late.',
    baseHp: 30,
    baseAtk: 15,
    baseDef: 2,
    xpReward: 35,
    speed: 1,
    behavior: 'ambush',
    drops: [{ itemId: 'abyssal_fang', chance: 0.05 }],
    floorMin: 7,
    floorMax: 12,
  },

  // --- BOSSES (every 5 floors) ---
  {
    id: 'boss_mother_spore',
    name: 'The Mother Spore',
    icon: '🧠',
    description: 'A colossal fungal brain that controls the hive.',
    baseHp: 80,
    baseAtk: 10,
    baseDef: 4,
    xpReward: 100,
    speed: 1,
    behavior: 'boss',
    isBoss: true,
    bossTitle: 'GUARDIAN OF THE SHALLOW DEPTHS',
    abilities: [
      { name: 'Summon Sporelings', type: 'summon', value: 2, cooldown: 5 },
      { name: 'Psychic Blast', type: 'ranged_attack', value: 8, cooldown: 3, range: 4 },
    ],
    drops: [{ itemId: 'fungal_blade', chance: 0.5 }, { itemId: 'chitin_mail', chance: 0.5 }],
    floorMin: 5,
    floorMax: 5,
  },
  {
    id: 'boss_crystal_king',
    name: 'The Crystal King',
    icon: '👑',
    description: 'A towering figure of living crystal. The caves bend to its will.',
    baseHp: 150,
    baseAtk: 16,
    baseDef: 8,
    xpReward: 250,
    speed: 1,
    behavior: 'boss',
    isBoss: true,
    bossTitle: 'LORD OF THE CRYSTAL DEPTHS',
    abilities: [
      { name: 'Crystal Storm', type: 'aoe', value: 10, cooldown: 4, range: 3 },
      { name: 'Regenerate', type: 'heal', value: 20, cooldown: 6 },
    ],
    drops: [{ itemId: 'crystal_axe', chance: 0.8 }, { itemId: 'mycelium_plate', chance: 0.4 }],
    floorMin: 10,
    floorMax: 10,
  },
  {
    id: 'boss_abyssal_maw',
    name: 'The Abyssal Maw',
    icon: '🕳️',
    description: 'The darkness itself has teeth. This is the heart of the Undergrowth.',
    baseHp: 250,
    baseAtk: 22,
    baseDef: 10,
    xpReward: 500,
    speed: 1,
    behavior: 'boss',
    isBoss: true,
    bossTitle: 'HEART OF THE ABYSS — FINAL BOSS',
    abilities: [
      { name: 'Void Breath', type: 'aoe', value: 15, cooldown: 3, range: 4 },
      { name: 'Consume', type: 'heal', value: 30, cooldown: 5 },
      { name: 'Blink', type: 'teleport', value: 0, cooldown: 4 },
    ],
    drops: [{ itemId: 'heart_of_undergrowth', chance: 1.0 }, { itemId: 'abyssal_carapace', chance: 0.6 }],
    floorMin: 15,
    floorMax: 15,
  },
];

export function getEnemyDef(id: string): EnemyDef | undefined {
  return ENEMIES.find(e => e.id === id);
}

// Get enemies that can spawn on a given floor
export function getEnemiesForFloor(floor: number): EnemyDef[] {
  return ENEMIES.filter(e => !e.isBoss && floor >= e.floorMin && floor <= e.floorMax);
}

// Get boss for a given floor (if any)
export function getBossForFloor(floor: number): EnemyDef | undefined {
  return ENEMIES.find(e => e.isBoss && e.floorMin === floor);
}

// Get items that can appear on a given floor
export function getItemsForFloor(floor: number): ItemDef[] {
  return ITEMS.filter(i => floor >= i.floorMin);
}

// Scale enemy stats based on floor depth
export function scaleEnemyStats(def: EnemyDef, floor: number): { hp: number; atk: number; def: number } {
  const scaling = 1 + (floor - 1) * 0.12;
  return {
    hp: Math.floor(def.baseHp * scaling),
    atk: Math.floor(def.baseAtk * scaling),
    def: Math.floor(def.baseDef * scaling),
  };
}
