// ============================================
// THE UNDERGROWTH — Entity Definitions
// All enemies and items in the game
// Expanded for 30 floors + endless mode
// 5 Biomes with unique creatures and loot
// ============================================

import { EnemyDef, ItemDef } from './types';

// ---- ITEMS (50+ total) ----
export const ITEMS: ItemDef[] = [
  // === CONSUMABLES (Healing & Buffs) ===
  {
    id: 'healing_moss',
    name: 'Healing Moss',
    icon: '🌿',
    description: 'Bioluminescent moss that mends wounds.',
    type: 'consumable',
    healAmount: 15,
    rarity: 'common',
    floorMin: 1,
  },
  {
    id: 'cave_berries',
    name: 'Cave Berries',
    icon: '🫐',
    description: 'Sweet berries that heal and cure poison.',
    type: 'consumable',
    healAmount: 10,
    statusEffect: { type: 'cure_poison', turnsLeft: 1, value: 0 },
    rarity: 'common',
    floorMin: 1,
  },
  {
    id: 'antidote_shroom',
    name: 'Antidote Shroom',
    icon: '☘️',
    description: 'Instantly neutralizes toxins.',
    type: 'consumable',
    statusEffect: { type: 'cure_poison', turnsLeft: 1, value: 0 },
    rarity: 'common',
    floorMin: 1,
  },
  {
    id: 'glowcap_elixir',
    name: 'Glowcap Elixir',
    icon: '🧪',
    description: 'Potent fungal brew that restores vitality.',
    type: 'consumable',
    healAmount: 40,
    rarity: 'uncommon',
    floorMin: 3,
  },
  {
    id: 'mycelium_wrap',
    name: 'Mycelium Wrap',
    icon: '🩹',
    description: 'Living bandage that regenerates wounds over time.',
    type: 'consumable',
    statusEffect: { type: 'regen', turnsLeft: 10, value: 3 },
    rarity: 'uncommon',
    floorMin: 2,
  },
  {
    id: 'strength_lichen',
    name: 'Strength Lichen',
    icon: '💪',
    description: 'Temporarily boosts attack power.',
    type: 'consumable',
    statusEffect: { type: 'strength', turnsLeft: 15, value: 4 },
    rarity: 'uncommon',
    floorMin: 3,
  },
  {
    id: 'stone_skin_paste',
    name: 'Stone Skin Paste',
    icon: '🪨',
    description: 'Hardens skin like stone, increasing defense.',
    type: 'consumable',
    statusEffect: { type: 'shield', turnsLeft: 10, value: 5 },
    rarity: 'uncommon',
    floorMin: 5,
  },
  {
    id: 'haste_spore',
    name: 'Haste Spore',
    icon: '⚡',
    description: 'Doubles your speed for a short time.',
    type: 'consumable',
    statusEffect: { type: 'haste', turnsLeft: 8, value: 2 },
    rarity: 'rare',
    floorMin: 7,
  },
  {
    id: 'crystal_water',
    name: 'Crystal Water',
    icon: '💎',
    description: 'Pure crystal essence. Heals and cures all debuffs.',
    type: 'consumable',
    healAmount: 30,
    statusEffect: { type: 'cure_poison', turnsLeft: 1, value: 0 },
    rarity: 'uncommon',
    floorMin: 13,
  },
  {
    id: 'magma_fruit',
    name: 'Magma Fruit',
    icon: '🌶️',
    description: 'Scorching fruit that restores considerable health.',
    type: 'consumable',
    healAmount: 50,
    rarity: 'uncommon',
    floorMin: 19,
  },
  {
    id: 'lava_draught',
    name: 'Lava Draught',
    icon: '🔥',
    description: 'Liquid fire that grants fiery aura.',
    type: 'consumable',
    statusEffect: { type: 'fire_aura', turnsLeft: 5, value: 5 },
    rarity: 'rare',
    floorMin: 19,
  },
  {
    id: 'abyssal_tear',
    name: 'Abyssal Tear',
    icon: '💧',
    description: 'A tear from the void itself. Restores significant health.',
    type: 'consumable',
    healAmount: 80,
    rarity: 'rare',
    floorMin: 25,
  },
  {
    id: 'void_essence',
    name: 'Void Essence',
    icon: '🕳️',
    description: 'Grants temporary invulnerability.',
    type: 'consumable',
    statusEffect: { type: 'invulnerable', turnsLeft: 3, value: 0 },
    rarity: 'legendary',
    floorMin: 25,
  },
  {
    id: 'primordial_nectar',
    name: 'Primordial Nectar',
    icon: '👑',
    description: 'Fully restores health and grants a protective shield.',
    type: 'consumable',
    healAmount: 999,
    statusEffect: { type: 'shield', turnsLeft: 10, value: 5 },
    rarity: 'legendary',
    floorMin: 8,
  },
  {
    id: 'phoenix_ash',
    name: 'Phoenix Ash',
    icon: '🔥',
    description: 'Auto-revives you once on death.',
    type: 'consumable',
    statusEffect: { type: 'invulnerable', turnsLeft: 999, value: 1 },
    rarity: 'legendary',
    floorMin: 20,
  },

  // === SCROLLS & THROWABLES ===
  {
    id: 'spore_bomb',
    name: 'Spore Bomb',
    icon: '💥',
    description: 'Explodes in toxic cloud, damaging nearby enemies.',
    type: 'scroll',
    scrollEffect: 'fireball',
    rarity: 'uncommon',
    floorMin: 2,
  },
  {
    id: 'luminous_draught',
    name: 'Luminous Draught',
    icon: '✨',
    description: 'Reveals the entire floor map.',
    type: 'scroll',
    scrollEffect: 'reveal_map',
    rarity: 'rare',
    floorMin: 3,
  },
  {
    id: 'blink_spore',
    name: 'Blink Spore',
    icon: '🌀',
    description: 'Teleports you to a random safe location.',
    type: 'scroll',
    scrollEffect: 'teleport',
    rarity: 'rare',
    floorMin: 2,
  },
  {
    id: 'frost_truffle',
    name: 'Frost Truffle',
    icon: '❄️',
    description: 'Freezes all enemies on the floor.',
    type: 'scroll',
    scrollEffect: 'freeze_all',
    rarity: 'rare',
    floorMin: 5,
  },
  {
    id: 'crystal_shard_scroll',
    name: 'Crystal Shard Scroll',
    icon: '💎',
    description: 'Shoots piercing crystal shards in a line.',
    type: 'scroll',
    scrollEffect: 'piercing_strike',
    rarity: 'uncommon',
    floorMin: 13,
  },
  {
    id: 'earthquake_scroll',
    name: 'Earthquake Scroll',
    icon: '🌍',
    description: 'Shakes ground, damaging and stunning all enemies.',
    type: 'scroll',
    scrollEffect: 'earthquake',
    rarity: 'rare',
    floorMin: 15,
  },
  {
    id: 'fire_wave_scroll',
    name: 'Fire Wave Scroll',
    icon: '🌊',
    description: 'Sends cone of fire outward.',
    type: 'scroll',
    scrollEffect: 'fire_wave',
    rarity: 'uncommon',
    floorMin: 19,
  },
  {
    id: 'shadow_step_scroll',
    name: 'Shadow Step Scroll',
    icon: '🗡️',
    description: 'Teleport behind enemy and backstab.',
    type: 'scroll',
    scrollEffect: 'backstab',
    rarity: 'rare',
    floorMin: 25,
  },
  {
    id: 'summon_spore_ally',
    name: 'Summon Spore Ally',
    icon: '🧬',
    description: 'Summons a powerful spore creature to fight for you.',
    type: 'scroll',
    scrollEffect: 'summon_ally',
    rarity: 'legendary',
    floorMin: 10,
  },
  {
    id: 'banish_scroll',
    name: 'Banish Scroll',
    icon: '⚫',
    description: 'Instantly banishes non-boss enemies.',
    type: 'scroll',
    scrollEffect: 'banish',
    rarity: 'rare',
    floorMin: 27,
  },

  // === WEAPONS (Shallow Caves) ===
  {
    id: 'stone_knife',
    name: 'Stone Knife',
    icon: '🔪',
    description: 'Crude blade chipped from cave rock.',
    type: 'equipment',
    equipSlot: 'weapon',
    atkBonus: 2,
    rarity: 'common',
    floorMin: 1,
  },
  {
    id: 'bone_club',
    name: 'Bone Club',
    icon: '🦴',
    description: 'Heavy femur from some unfortunate beast.',
    type: 'equipment',
    equipSlot: 'weapon',
    atkBonus: 3,
    rarity: 'common',
    floorMin: 1,
  },

  // === WEAPONS (Fungal Forest) ===
  {
    id: 'fungal_blade',
    name: 'Fungal Blade',
    icon: '⚔️',
    description: 'Sword grown from hardened mycelium. Razor-sharp.',
    type: 'equipment',
    equipSlot: 'weapon',
    atkBonus: 5,
    rarity: 'uncommon',
    floorMin: 3,
  },
  {
    id: 'spore_whip',
    name: 'Spore Whip',
    icon: '🪢',
    description: 'Living whip made of hardened fungal strands.',
    type: 'equipment',
    equipSlot: 'weapon',
    atkBonus: 6,
    rarity: 'uncommon',
    floorMin: 7,
  },
  {
    id: 'mycelium_scythe',
    name: 'Mycelium Scythe',
    icon: '🌾',
    description: 'Curved blade of living mycelium. Reaps souls.',
    type: 'equipment',
    equipSlot: 'weapon',
    atkBonus: 8,
    rarity: 'rare',
    floorMin: 9,
  },

  // === WEAPONS (Crystal Caverns) ===
  {
    id: 'crystal_rapier',
    name: 'Crystal Rapier',
    icon: '🗡️',
    description: 'Elegant blade of pure cave crystal.',
    type: 'equipment',
    equipSlot: 'weapon',
    atkBonus: 9,
    rarity: 'uncommon',
    floorMin: 13,
  },
  {
    id: 'prism_greatsword',
    name: 'Prism Greatsword',
    icon: '⚔️',
    description: 'Massive sword that refracts light into cutting beams.',
    type: 'equipment',
    equipSlot: 'weapon',
    atkBonus: 12,
    rarity: 'rare',
    floorMin: 15,
  },

  // === WEAPONS (Lava Depths) ===
  {
    id: 'magma_hammer',
    name: 'Magma Hammer',
    icon: '🔨',
    description: 'Hammer of molten stone. Burns on impact.',
    type: 'equipment',
    equipSlot: 'weapon',
    atkBonus: 11,
    rarity: 'uncommon',
    floorMin: 19,
  },
  {
    id: 'obsidian_edge',
    name: 'Obsidian Edge',
    icon: '🗡️',
    description: 'Wickedly sharp blade of volcanic glass.',
    type: 'equipment',
    equipSlot: 'weapon',
    atkBonus: 14,
    rarity: 'rare',
    floorMin: 21,
  },

  // === WEAPONS (The Abyss) ===
  {
    id: 'abyssal_fang',
    name: 'Abyssal Fang',
    icon: '🗡️',
    description: 'Tooth from something that should not exist. Hums with power.',
    type: 'equipment',
    equipSlot: 'weapon',
    atkBonus: 16,
    rarity: 'rare',
    floorMin: 25,
  },
  {
    id: 'void_reaper',
    name: 'Void Reaper',
    icon: '💀',
    description: 'Scythe born from the abyss itself. Inevitably deadly.',
    type: 'equipment',
    equipSlot: 'weapon',
    atkBonus: 20,
    rarity: 'legendary',
    floorMin: 28,
  },

  // === ARMOR (Shallow Caves) ===
  {
    id: 'bark_vest',
    name: 'Bark Vest',
    icon: '🪵',
    description: 'Woven bark strips offer basic protection.',
    type: 'equipment',
    equipSlot: 'armor',
    defBonus: 2,
    rarity: 'common',
    floorMin: 1,
  },

  // === ARMOR (Fungal Forest) ===
  {
    id: 'chitin_mail',
    name: 'Chitin Mail',
    icon: '🛡️',
    description: 'Armor plating harvested from giant cave beetles.',
    type: 'equipment',
    equipSlot: 'armor',
    defBonus: 4,
    rarity: 'uncommon',
    floorMin: 3,
  },
  {
    id: 'fungal_plate',
    name: 'Fungal Plate',
    icon: '🧥',
    description: 'Dense fungal armor that regenerates over time.',
    type: 'equipment',
    equipSlot: 'armor',
    defBonus: 5,
    hpBonus: 10,
    rarity: 'uncommon',
    floorMin: 7,
  },
  {
    id: 'spore_guard',
    name: 'Spore Guard',
    icon: '🛡️',
    description: 'Armor wreathed in protective spore clouds.',
    type: 'equipment',
    equipSlot: 'armor',
    defBonus: 7,
    hpBonus: 15,
    rarity: 'rare',
    floorMin: 9,
  },

  // === ARMOR (Crystal Caverns) ===
  {
    id: 'crystal_guard',
    name: 'Crystal Guard',
    icon: '💎',
    description: 'Plate made of interlocking crystal segments.',
    type: 'equipment',
    equipSlot: 'armor',
    defBonus: 8,
    rarity: 'uncommon',
    floorMin: 13,
  },
  {
    id: 'prism_plate',
    name: 'Prism Plate',
    icon: '🔷',
    description: 'Prismatic armor that reflects damage back.',
    type: 'equipment',
    equipSlot: 'armor',
    defBonus: 11,
    hpBonus: 20,
    rarity: 'rare',
    floorMin: 16,
  },

  // === ARMOR (Lava Depths) ===
  {
    id: 'magma_shell',
    name: 'Magma Shell',
    icon: '🔥',
    description: 'Hardened lava plating. Sizzles with heat.',
    type: 'equipment',
    equipSlot: 'armor',
    defBonus: 10,
    rarity: 'uncommon',
    floorMin: 19,
  },
  {
    id: 'volcanic_plate',
    name: 'Volcanic Plate',
    icon: '🌋',
    description: 'Armor forged in magma. Grants fire resistance.',
    type: 'equipment',
    equipSlot: 'armor',
    defBonus: 13,
    hpBonus: 25,
    rarity: 'rare',
    floorMin: 22,
  },

  // === ARMOR (The Abyss) ===
  {
    id: 'abyssal_carapace',
    name: 'Abyssal Carapace',
    icon: '🦠',
    description: 'Living darkness itself. It watches your back.',
    type: 'equipment',
    equipSlot: 'armor',
    defBonus: 15,
    hpBonus: 30,
    rarity: 'rare',
    floorMin: 25,
  },
  {
    id: 'void_mantle',
    name: 'Void Mantle',
    icon: '⚫',
    description: 'Cloak of pure void. Existence itself bends around it.',
    type: 'equipment',
    equipSlot: 'armor',
    defBonus: 18,
    hpBonus: 40,
    rarity: 'legendary',
    floorMin: 28,
  },

  // === ACCESSORIES ===
  {
    id: 'glowstone_ring',
    name: 'Glowstone Ring',
    icon: '💍',
    description: 'Extends your field of vision slightly.',
    type: 'equipment',
    equipSlot: 'accessory',
    hpBonus: 5,
    rarity: 'common',
    floorMin: 2,
  },
  {
    id: 'spider_silk_band',
    name: 'Spider Silk Band',
    icon: '🕸️',
    description: 'Woven silk from giant spiders. Boosts offense and defense.',
    type: 'equipment',
    equipSlot: 'accessory',
    atkBonus: 2,
    defBonus: 2,
    rarity: 'uncommon',
    floorMin: 4,
  },
  {
    id: 'spore_amulet',
    name: 'Spore Amulet',
    icon: '📿',
    description: 'Pendant that pulses with fungal energy. Boosts all stats.',
    type: 'equipment',
    equipSlot: 'accessory',
    atkBonus: 2,
    defBonus: 2,
    hpBonus: 10,
    rarity: 'rare',
    floorMin: 7,
  },
  {
    id: 'crystal_lens',
    name: 'Crystal Lens',
    icon: '🔍',
    description: 'Magnifying lens of crystal. Enhances precision.',
    type: 'equipment',
    equipSlot: 'accessory',
    atkBonus: 3,
    hpBonus: 5,
    rarity: 'uncommon',
    floorMin: 13,
  },
  {
    id: 'lava_heart_pendant',
    name: 'Lava Heart Pendant',
    icon: '❤️',
    description: 'Heart of magma itself. Grants strength and durability.',
    type: 'equipment',
    equipSlot: 'accessory',
    atkBonus: 4,
    defBonus: 4,
    hpBonus: 15,
    rarity: 'rare',
    floorMin: 19,
  },
  {
    id: 'void_eye',
    name: 'Void Eye',
    icon: '👁️',
    description: 'All-seeing eye from beyond. Grants immense power.',
    type: 'equipment',
    equipSlot: 'accessory',
    atkBonus: 5,
    defBonus: 5,
    rarity: 'rare',
    floorMin: 25,
  },
  {
    id: 'heart_of_undergrowth',
    name: 'Heart of the Undergrowth',
    icon: '💠',
    description: 'Living core of the mycelium network. Immense power.',
    type: 'equipment',
    equipSlot: 'accessory',
    atkBonus: 8,
    defBonus: 8,
    hpBonus: 50,
    rarity: 'legendary',
    floorMin: 28,
  },
  {
    id: 'ring_of_second_chances',
    name: 'Ring of Second Chances',
    icon: '💫',
    description: 'Auto-revive once on death. Grants life force.',
    type: 'equipment',
    equipSlot: 'accessory',
    statusEffect: { type: 'invulnerable', turnsLeft: 999, value: 1 },
    hpBonus: 20,
    rarity: 'legendary',
    floorMin: 20,
  },

  // === KEYS ===
  {
    id: 'cave_key',
    name: 'Cave Key',
    icon: '🗝️',
    description: 'A rusty key. Opens locked chests in shallow caves.',
    type: 'key',
    rarity: 'common',
    floorMin: 1,
  },
  {
    id: 'crystal_key',
    name: 'Crystal Key',
    icon: '🔑',
    description: 'Glowing key of pure crystal. Opens crystal locks.',
    type: 'key',
    rarity: 'uncommon',
    floorMin: 13,
  },
  {
    id: 'abyssal_key',
    name: 'Abyssal Key',
    icon: '⚫',
    description: 'Key from the abyss itself. Opens forbidden locks.',
    type: 'key',
    rarity: 'rare',
    floorMin: 25,
  },
];

export function getItemDef(id: string): ItemDef | undefined {
  return ITEMS.find(i => i.id === id);
}

// ---- ENEMIES (30+ regular + 5 bosses) ----
export const ENEMIES: EnemyDef[] = [
  // ============================================
  // BIOME 1: SHALLOW CAVES (F1-6)
  // ============================================
  {
    id: 'cave_rat',
    name: 'Cave Rat',
    icon: '🐀',
    description: 'Scrawny rodent with glowing eyes. Skitters nervously.',
    baseHp: 8,
    baseAtk: 2,
    baseDef: 0,
    xpReward: 5,
    speed: 1,
    behavior: 'wander',
    drops: [{ itemId: 'healing_moss', chance: 0.3 }],
    floorMin: 1,
    floorMax: 4,
  },
  {
    id: 'glow_beetle',
    name: 'Glow Beetle',
    icon: '🪲',
    description: 'Luminescent beetle with sharp mandibles.',
    baseHp: 12,
    baseAtk: 3,
    baseDef: 1,
    xpReward: 8,
    speed: 1,
    behavior: 'chase',
    drops: [{ itemId: 'healing_moss', chance: 0.2 }],
    floorMin: 1,
    floorMax: 5,
  },
  {
    id: 'spore_bat',
    name: 'Spore Bat',
    icon: '🦇',
    description: 'Erratic flight makes it hard to hit.',
    baseHp: 6,
    baseAtk: 4,
    baseDef: 0,
    xpReward: 7,
    speed: 1,
    behavior: 'wander',
    drops: [],
    floorMin: 1,
    floorMax: 5,
  },
  {
    id: 'mushroom_walker',
    name: 'Mushroom Walker',
    icon: '🍄',
    description: 'Ambulatory fungus that shambles toward you.',
    baseHp: 20,
    baseAtk: 4,
    baseDef: 2,
    xpReward: 12,
    speed: 1,
    behavior: 'chase',
    drops: [{ itemId: 'healing_moss', chance: 0.4 }, { itemId: 'cave_key', chance: 0.1 }],
    floorMin: 2,
    floorMax: 6,
  },
  {
    id: 'acid_slug',
    name: 'Acid Slug',
    icon: '🐛',
    description: 'Leaves corrosive trail. Slow but deadly.',
    baseHp: 25,
    baseAtk: 6,
    baseDef: 1,
    xpReward: 15,
    speed: 2,
    behavior: 'chase',
    drops: [{ itemId: 'spore_bomb', chance: 0.15 }],
    floorMin: 2,
    floorMax: 7,
  },
  {
    id: 'cave_spider',
    name: 'Cave Spider',
    icon: '🕷️',
    description: 'Waits in ambush, then strikes with venomous fangs.',
    baseHp: 14,
    baseAtk: 5,
    baseDef: 1,
    xpReward: 12,
    speed: 1,
    behavior: 'ambush',
    drops: [{ itemId: 'mycelium_wrap', chance: 0.15 }],
    floorMin: 2,
    floorMax: 6,
  },

  // ============================================
  // BIOME 2: FUNGAL FOREST (F7-12)
  // ============================================
  {
    id: 'toxic_toadstool',
    name: 'Toxic Toadstool',
    icon: '🟤',
    description: 'Putrid fungal creature that poisons on contact.',
    baseHp: 30,
    baseAtk: 7,
    baseDef: 3,
    xpReward: 18,
    speed: 1,
    behavior: 'chase',
    abilities: [{ name: 'Poison Cloud', type: 'aoe', value: 3, cooldown: 4, range: 2 }],
    drops: [{ itemId: 'antidote_shroom', chance: 0.2 }],
    floorMin: 7,
    floorMax: 10,
  },
  {
    id: 'spore_cloud',
    name: 'Spore Cloud',
    icon: '🌫️',
    description: 'Amorphous mass of toxic spores. Spreads poison.',
    baseHp: 20,
    baseAtk: 5,
    baseDef: 0,
    xpReward: 16,
    speed: 1,
    behavior: 'wander',
    abilities: [{ name: 'Spore Spread', type: 'aoe', value: 2, cooldown: 3, range: 3 }],
    drops: [],
    floorMin: 7,
    floorMax: 11,
  },
  {
    id: 'fungal_brute',
    name: 'Fungal Brute',
    icon: '💀',
    description: 'Massive fungal mass with club-like limbs.',
    baseHp: 45,
    baseAtk: 9,
    baseDef: 4,
    xpReward: 22,
    speed: 1,
    behavior: 'chase',
    drops: [{ itemId: 'fungal_blade', chance: 0.12 }],
    floorMin: 8,
    floorMax: 12,
  },
  {
    id: 'vine_strangler',
    name: 'Vine Strangler',
    icon: '🌿',
    description: 'Writhing vines that constrict and crush.',
    baseHp: 25,
    baseAtk: 10,
    baseDef: 2,
    xpReward: 20,
    speed: 1,
    behavior: 'ambush',
    abilities: [{ name: 'Strangle', type: 'ranged_attack', value: 5, cooldown: 3, range: 1 }],
    drops: [{ itemId: 'cave_berries', chance: 0.15 }],
    floorMin: 9,
    floorMax: 12,
  },
  {
    id: 'mycoid_shaman',
    name: 'Mycoid Shaman',
    icon: '🧙',
    description: 'Sentient fungal creature that heals its allies.',
    baseHp: 22,
    baseAtk: 6,
    baseDef: 2,
    xpReward: 18,
    speed: 1,
    behavior: 'chase',
    abilities: [
      { name: 'Healing Spore', type: 'heal', value: 8, cooldown: 4, range: 3 },
      { name: 'Spore Projectile', type: 'ranged_attack', value: 4, cooldown: 2, range: 4 },
    ],
    drops: [{ itemId: 'glowcap_elixir', chance: 0.1 }],
    floorMin: 10,
    floorMax: 12,
  },

  // ============================================
  // BIOME 3: CRYSTAL CAVERNS (F13-18)
  // ============================================
  {
    id: 'crystal_golem',
    name: 'Crystal Golem',
    icon: '🪨',
    description: 'Animated cave crystals. Extremely tough.',
    baseHp: 60,
    baseAtk: 10,
    baseDef: 8,
    xpReward: 25,
    speed: 2,
    behavior: 'patrol',
    drops: [{ itemId: 'crystal_key', chance: 0.15 }],
    floorMin: 13,
    floorMax: 17,
  },
  {
    id: 'phantom_spore',
    name: 'Phantom Spore',
    icon: '👻',
    description: 'Ghostly mass of spores. Partially intangible.',
    baseHp: 25,
    baseAtk: 12,
    baseDef: 1,
    xpReward: 20,
    speed: 1,
    behavior: 'chase',
    abilities: [{ name: 'Phase Strike', type: 'ranged_attack', value: 6, cooldown: 2, range: 1 }],
    drops: [{ itemId: 'blink_spore', chance: 0.2 }],
    floorMin: 13,
    floorMax: 18,
  },
  {
    id: 'prism_spider',
    name: 'Prism Spider',
    icon: '🕸️',
    description: 'Giant spider made of crystalline strands.',
    baseHp: 35,
    baseAtk: 14,
    baseDef: 3,
    xpReward: 24,
    speed: 1,
    behavior: 'ambush',
    abilities: [{ name: 'Web Trap', type: 'aoe', value: 4, cooldown: 4, range: 2 }],
    drops: [{ itemId: 'spider_silk_band', chance: 0.12 }],
    floorMin: 14,
    floorMax: 18,
  },
  {
    id: 'shard_elemental',
    name: 'Shard Elemental',
    icon: '💎',
    description: 'Creature of pure crystal energy. Shoots shards.',
    baseHp: 30,
    baseAtk: 11,
    baseDef: 4,
    xpReward: 22,
    speed: 1,
    behavior: 'chase',
    abilities: [
      { name: 'Crystal Burst', type: 'ranged_attack', value: 6, cooldown: 3, range: 4 },
      { name: 'Shard Storm', type: 'aoe', value: 4, cooldown: 5, range: 2 },
    ],
    drops: [{ itemId: 'crystal_water', chance: 0.15 }],
    floorMin: 15,
    floorMax: 18,
  },
  {
    id: 'crystal_sentinel',
    name: 'Crystal Sentinel',
    icon: '⚔️',
    description: 'Guardian made of crystalline matter. Tireless defender.',
    baseHp: 50,
    baseAtk: 13,
    baseDef: 7,
    xpReward: 26,
    speed: 1,
    behavior: 'patrol',
    drops: [{ itemId: 'crystal_rapier', chance: 0.08 }],
    floorMin: 16,
    floorMax: 18,
  },

  // ============================================
  // BIOME 4: LAVA DEPTHS (F19-24)
  // ============================================
  {
    id: 'magma_slug',
    name: 'Magma Slug',
    icon: '🔥',
    description: 'Enormous molten slug. Moves slowly but inexorably.',
    baseHp: 55,
    baseAtk: 15,
    baseDef: 5,
    xpReward: 28,
    speed: 2,
    behavior: 'chase',
    abilities: [{ name: 'Lava Spray', type: 'aoe', value: 6, cooldown: 3, range: 2 }],
    drops: [{ itemId: 'magma_fruit', chance: 0.15 }],
    floorMin: 19,
    floorMax: 22,
  },
  {
    id: 'fire_imp',
    name: 'Fire Imp',
    icon: '😈',
    description: 'Demonic creature wreathed in flames.',
    baseHp: 30,
    baseAtk: 16,
    baseDef: 3,
    xpReward: 24,
    speed: 1,
    behavior: 'wander',
    abilities: [
      { name: 'Fireball', type: 'ranged_attack', value: 7, cooldown: 2, range: 3 },
      { name: 'Flame Burst', type: 'aoe', value: 5, cooldown: 4, range: 2 },
    ],
    drops: [{ itemId: 'lava_draught', chance: 0.12 }],
    floorMin: 19,
    floorMax: 23,
  },
  {
    id: 'obsidian_golem',
    name: 'Obsidian Golem',
    icon: '🗿',
    description: 'Massive construct of black volcanic glass.',
    baseHp: 80,
    baseAtk: 14,
    baseDef: 10,
    xpReward: 32,
    speed: 2,
    behavior: 'patrol',
    drops: [{ itemId: 'obsidian_edge', chance: 0.08 }],
    floorMin: 20,
    floorMax: 24,
  },
  {
    id: 'flame_wraith',
    name: 'Flame Wraith',
    icon: '🌋',
    description: 'Ghostly creature of pure fire and fury.',
    baseHp: 40,
    baseAtk: 18,
    baseDef: 4,
    xpReward: 30,
    speed: 1,
    behavior: 'chase',
    abilities: [
      { name: 'Inferno', type: 'aoe', value: 8, cooldown: 4, range: 2 },
      { name: 'Flame Strike', type: 'ranged_attack', value: 7, cooldown: 2, range: 1 },
    ],
    drops: [{ itemId: 'phoenix_ash', chance: 0.1 }],
    floorMin: 21,
    floorMax: 24,
  },
  {
    id: 'lava_serpent',
    name: 'Lava Serpent',
    icon: '🐍',
    description: 'Reptilian creature of liquid magma.',
    baseHp: 50,
    baseAtk: 17,
    baseDef: 6,
    xpReward: 28,
    speed: 1,
    behavior: 'chase',
    abilities: [{ name: 'Lava Whip', type: 'ranged_attack', value: 8, cooldown: 3, range: 2 }],
    drops: [{ itemId: 'magma_fruit', chance: 0.15 }],
    floorMin: 22,
    floorMax: 24,
  },

  // ============================================
  // BIOME 5: THE ABYSS (F25-30)
  // ============================================
  {
    id: 'shadow_stalker',
    name: 'Shadow Stalker',
    icon: '🌑',
    description: 'Only visible when it attacks. By then, too late.',
    baseHp: 45,
    baseAtk: 20,
    baseDef: 5,
    xpReward: 35,
    speed: 1,
    behavior: 'ambush',
    abilities: [{ name: 'Shadow Strike', type: 'ranged_attack', value: 10, cooldown: 3, range: 1 }],
    drops: [{ itemId: 'abyssal_fang', chance: 0.12 }],
    floorMin: 25,
    floorMax: 29,
  },
  {
    id: 'void_tendril',
    name: 'Void Tendril',
    icon: '🦑',
    description: 'Writhing tentacle from beyond space.',
    baseHp: 60,
    baseAtk: 18,
    baseDef: 8,
    xpReward: 36,
    speed: 1,
    behavior: 'chase',
    abilities: [
      { name: 'Void Grasp', type: 'ranged_attack', value: 9, cooldown: 2, range: 2 },
      { name: 'Void Pulse', type: 'aoe', value: 7, cooldown: 4, range: 2 },
    ],
    drops: [{ itemId: 'abyssal_tear', chance: 0.15 }],
    floorMin: 25,
    floorMax: 29,
  },
  {
    id: 'abyssal_eye',
    name: 'Abyssal Eye',
    icon: '👁️',
    description: 'Floating eye from the void. Sees all, judges all.',
    baseHp: 35,
    baseAtk: 22,
    baseDef: 3,
    xpReward: 32,
    speed: 1,
    behavior: 'chase',
    abilities: [
      { name: 'Void Gaze', type: 'ranged_attack', value: 10, cooldown: 2, range: 5 },
      { name: 'Reality Tear', type: 'aoe', value: 8, cooldown: 4, range: 3 },
    ],
    drops: [{ itemId: 'void_eye', chance: 0.15 }],
    floorMin: 26,
    floorMax: 30,
  },
  {
    id: 'deep_crawler',
    name: 'Deep Crawler',
    icon: '🦂',
    description: 'Colossal centipede from the deepest darkness.',
    baseHp: 70,
    baseAtk: 19,
    baseDef: 7,
    xpReward: 38,
    speed: 1,
    behavior: 'chase',
    abilities: [
      { name: 'Piercing Strike', type: 'ranged_attack', value: 10, cooldown: 2, range: 1 },
      { name: 'Segmented Assault', type: 'aoe', value: 6, cooldown: 5, range: 2 },
    ],
    drops: [{ itemId: 'abyssal_carapace', chance: 0.12 }],
    floorMin: 27,
    floorMax: 30,
  },
  {
    id: 'eldritch_horror',
    name: 'Eldritch Horror',
    icon: '🌀',
    description: 'Reality bends around it. It should not exist.',
    baseHp: 90,
    baseAtk: 21,
    baseDef: 9,
    xpReward: 42,
    speed: 1,
    behavior: 'chase',
    abilities: [
      { name: 'Void Eruption', type: 'aoe', value: 10, cooldown: 3, range: 3 },
      { name: 'Reality Warp', type: 'teleport', value: 0, cooldown: 4, range: 5 },
      { name: 'Abyssal Touch', type: 'ranged_attack', value: 12, cooldown: 2, range: 1 },
    ],
    drops: [{ itemId: 'void_essence', chance: 0.15 }],
    floorMin: 28,
    floorMax: 30,
  },

  // ============================================
  // BOSSES (Every 6 floors)
  // ============================================
  {
    id: 'boss_brood_mother',
    name: 'The Brood Mother',
    icon: '🕷️',
    description: 'Queen of the spiders. All arachnids answer to her.',
    baseHp: 100,
    baseAtk: 12,
    baseDef: 5,
    xpReward: 150,
    speed: 1,
    behavior: 'boss',
    isBoss: true,
    bossTitle: 'GUARDIAN OF THE SHALLOW CAVES',
    abilities: [
      { name: 'Summon Spiderlings', type: 'summon', value: 3, cooldown: 5, range: 0 },
      { name: 'Web Barrage', type: 'aoe', value: 7, cooldown: 3, range: 3 },
      { name: 'Venomous Fang', type: 'ranged_attack', value: 10, cooldown: 2, range: 1 },
    ],
    drops: [
      { itemId: 'bone_club', chance: 0.5 },
      { itemId: 'bark_vest', chance: 0.5 },
      { itemId: 'cave_key', chance: 1.0 },
    ],
    floorMin: 6,
    floorMax: 6,
  },
  {
    id: 'boss_mother_spore',
    name: 'The Mother Spore',
    icon: '🧠',
    description: 'Colossal fungal brain that controls the mycelial hive.',
    baseHp: 150,
    baseAtk: 14,
    baseDef: 6,
    xpReward: 200,
    speed: 1,
    behavior: 'boss',
    isBoss: true,
    bossTitle: 'SOVEREIGN OF THE FUNGAL FOREST',
    abilities: [
      { name: 'Summon Sporelings', type: 'summon', value: 4, cooldown: 5, range: 0 },
      { name: 'Psychic Blast', type: 'ranged_attack', value: 10, cooldown: 3, range: 4 },
      { name: 'Spore Explosion', type: 'aoe', value: 9, cooldown: 4, range: 3 },
      { name: 'Hive Regenerate', type: 'heal', value: 15, cooldown: 6, range: 0 },
    ],
    drops: [
      { itemId: 'fungal_blade', chance: 0.7 },
      { itemId: 'fungal_plate', chance: 0.5 },
      { itemId: 'spore_bomb', chance: 1.0 },
    ],
    floorMin: 12,
    floorMax: 12,
  },
  {
    id: 'boss_crystal_king',
    name: 'The Crystal King',
    icon: '👑',
    description: 'Towering figure of living crystal. Reality refracts around it.',
    baseHp: 200,
    baseAtk: 18,
    baseDef: 10,
    xpReward: 300,
    speed: 1,
    behavior: 'boss',
    isBoss: true,
    bossTitle: 'SOVEREIGN OF THE CRYSTAL CAVERNS',
    abilities: [
      { name: 'Crystal Storm', type: 'aoe', value: 12, cooldown: 4, range: 3 },
      { name: 'Prismatic Beam', type: 'ranged_attack', value: 11, cooldown: 2, range: 5 },
      { name: 'Crystalline Regenerate', type: 'heal', value: 20, cooldown: 5, range: 0 },
      { name: 'Shard Barrage', type: 'aoe', value: 10, cooldown: 3, range: 4 },
    ],
    drops: [
      { itemId: 'crystal_rapier', chance: 0.8 },
      { itemId: 'prism_plate', chance: 0.6 },
      { itemId: 'crystal_key', chance: 1.0 },
    ],
    floorMin: 18,
    floorMax: 18,
  },
  {
    id: 'boss_infernal',
    name: 'The Infernal',
    icon: '🔥',
    description: 'Pure incarnation of heat and rage. Fire itself made conscious.',
    baseHp: 280,
    baseAtk: 22,
    baseDef: 12,
    xpReward: 400,
    speed: 1,
    behavior: 'boss',
    isBoss: true,
    bossTitle: 'MASTER OF THE LAVA DEPTHS',
    abilities: [
      { name: 'Inferno Eruption', type: 'aoe', value: 14, cooldown: 4, range: 3 },
      { name: 'Summon Fire Imps', type: 'summon', value: 3, cooldown: 6, range: 0 },
      { name: 'Fiery Wrath', type: 'ranged_attack', value: 14, cooldown: 2, range: 1 },
      { name: 'Enrage', type: 'buff', value: 4, cooldown: 5, range: 0 },
      { name: 'Magma Recovery', type: 'heal', value: 25, cooldown: 6, range: 0 },
    ],
    drops: [
      { itemId: 'obsidian_edge', chance: 0.8 },
      { itemId: 'volcanic_plate', chance: 0.6 },
      { itemId: 'phoenix_ash', chance: 1.0 },
    ],
    floorMin: 24,
    floorMax: 24,
  },
  {
    id: 'boss_abyssal_maw',
    name: 'The Abyssal Maw',
    icon: '🕳️',
    description: 'Darkness itself has teeth. Heart of the Undergrowth.',
    baseHp: 400,
    baseAtk: 28,
    baseDef: 14,
    xpReward: 600,
    speed: 1,
    behavior: 'boss',
    isBoss: true,
    bossTitle: 'FINAL GUARDIAN — HEART OF THE ABYSS',
    abilities: [
      { name: 'Void Breath', type: 'aoe', value: 16, cooldown: 3, range: 4 },
      { name: 'Consume', type: 'heal', value: 35, cooldown: 5, range: 0 },
      { name: 'Blink', type: 'teleport', value: 0, cooldown: 4, range: 0 },
      { name: 'Summon Voids', type: 'summon', value: 2, cooldown: 6, range: 0 },
      { name: 'Reality Tear', type: 'aoe', value: 18, cooldown: 5, range: 3 },
      { name: 'Abyssal Ascendant', type: 'buff', value: 5, cooldown: 7, range: 0 },
    ],
    drops: [
      { itemId: 'void_reaper', chance: 1.0 },
      { itemId: 'void_mantle', chance: 1.0 },
      { itemId: 'heart_of_undergrowth', chance: 0.8 },
      { itemId: 'abyssal_key', chance: 1.0 },
    ],
    floorMin: 30,
    floorMax: 30,
  },
];

export function getEnemyDef(id: string): EnemyDef | undefined {
  return ENEMIES.find(e => e.id === id);
}

// Get enemies that can spawn on a given floor
export function getEnemiesForFloor(floor: number): EnemyDef[] {
  return ENEMIES.filter(e => !e.isBoss && floor >= e.floorMin && floor <= e.floorMax);
}

// Get boss for a given floor (if any)
export function getBossForFloor(floor: number): EnemyDef | undefined {
  return ENEMIES.find(e => e.isBoss && e.floorMin === floor);
}

// Get items that can appear on a given floor
export function getItemsForFloor(floor: number): ItemDef[] {
  return ITEMS.filter(i => floor >= i.floorMin);
}

// Scale enemy stats based on floor depth
// Standard floors (1-30): 1 + (floor - 1) * 0.08
// Endless mode (floor > 30): aggressive scaling
export function scaleEnemyStats(
  def: EnemyDef,
  floor: number
): { hp: number; atk: number; def: number } {
  let scaling: number;

  if (floor <= 30) {
    // Standard scaling: slower progression across 30 floors
    scaling = 1 + (floor - 1) * 0.08;
  } else {
    // Endless mode: aggressive scaling after floor 30
    scaling = 1 + (30 - 1) * 0.08 + (floor - 30) * 0.15;
  }

  return {
    hp: Math.floor(def.baseHp * scaling),
    atk: Math.floor(def.baseAtk * scaling),
    def: Math.floor(def.baseDef * scaling),
  };
}
